#!/usr/bin/env python3
"""Build deterministic CARTA Atlas terrain assets from a pinned elevation source.

Terrain is context before it is interpretation. This script turns one pinned
Copernicus DEM GLO-30 tile set into restrained shaded-relief and sparse-contour
products for each bounded Atlas terrain extent, and records every processing
parameter back into the dataset manifest so the assets can be regenerated byte
for byte.

The contract these products live under is documented in
`docs/atlas-terrain-foundation.md`. Nothing here may author a wine claim.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from pathlib import Path
from typing import Any, Iterable

GEOSPATIAL_IMPORT_ERROR: ImportError | None = None

try:
    import numpy as np
    import contourpy
    import rasterio
    from PIL import Image
    from pyproj import Transformer
    from rasterio.enums import Resampling
    from rasterio.merge import merge as merge_rasters
    from rasterio.transform import from_origin
    from rasterio.warp import reproject
    from shapely.geometry import LineString
except ImportError as exc:  # pragma: no cover - exercised by clean validation environments
    GEOSPATIAL_IMPORT_ERROR = exc

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_atlas import build_provenance  # noqa: E402  (shared provenance projection)

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_DIR = ROOT / "data/geography/datasets"
PUBLIC_DATA_DIR = ROOT / "atlas-app/public/data"
DEFAULT_SOURCE_DIR = ROOT / ".cache/atlas/terrain"

TERRAIN_DATASET_ID = "spatial-dataset:copernicus-dem-glo30-2022-05-09"
TERRAIN_MANIFEST_PATH = MANIFEST_DIR / "copernicus-dem-glo30-2022-05-09.json"
TERRAIN_RELEASE = "atlas-run-09-beaujolais-world"

# --- Bounded proof extents --------------------------------------------------
# Each extent is presentation context, never a wine-region boundary. Source
# files are explicit so disconnected proofs are never mosaicked into a false
# France-wide terrain surface.
TERRAIN_EXTENTS = (
    {
        "id": "bearn-jurancon",
        "label": "Béarn / Jurançon",
        "bbox": (-1.75, 42.70, 0.25, 43.80),
        "description": (
            "Béarn, Jurançon, Pacherenc du Vic-Bilh, Irouléguy and the western "
            "Pyrenean front. Outside this bounded extent CARTA Atlas has no terrain."
        ),
        "source_files": (
            "Copernicus_DSM_COG_10_N42_00_E000_00_DEM.tif",
            "Copernicus_DSM_COG_10_N42_00_W001_00_DEM.tif",
            "Copernicus_DSM_COG_10_N42_00_W002_00_DEM.tif",
            "Copernicus_DSM_COG_10_N43_00_E000_00_DEM.tif",
            "Copernicus_DSM_COG_10_N43_00_W001_00_DEM.tif",
            "Copernicus_DSM_COG_10_N43_00_W002_00_DEM.tif",
        ),
        "hillshade_path": PUBLIC_DATA_DIR / "atlas-terrain-hillshade.png",
        "contour_path": PUBLIC_DATA_DIR / "atlas-terrain-contours.geojson",
    },
    {
        "id": "beaujolais",
        "label": "Beaujolais",
        "bbox": (4.05, 45.55, 4.98, 46.48),
        "description": (
            "A bounded Beaujolais context from the southern wine country through "
            "the ten-cru corridor, with the Monts du Beaujolais to the west and "
            "Saône-facing low country to the east. It is not a wine boundary."
        ),
        "source_files": (
            "Copernicus_DSM_COG_10_N45_00_E004_00_DEM.tif",
            "Copernicus_DSM_COG_10_N46_00_E004_00_DEM.tif",
        ),
        "hillshade_path": PUBLIC_DATA_DIR / "atlas-terrain-beaujolais-hillshade.png",
        "contour_path": PUBLIC_DATA_DIR / "atlas-terrain-beaujolais-contours.geojson",
    },
)
SOURCE_CLIP_BUFFER_DEGREES = 0.05

# --- Derivation parameters (every one of these is pinned into the manifest) ---
PIXEL_SIZE_METRES_EPSG3857 = 150.0
HILLSHADE_AZIMUTH_DEGREES = 315.0
HILLSHADE_ALTITUDE_DEGREES = 45.0
HILLSHADE_Z_FACTOR = 1.0
SHADOW_INK = (58, 51, 44)
LIGHT_INK = (255, 253, 248)
# Deviation from flat-ground illumination that maps to full overlay strength.
# Tuned on the Jurançon foothills: gentle vineyard slopes must register, without
# the Pyrenean faces collapsing into a solid mass.
HILLSHADE_RESPONSE_SCALE = 0.32
SHADOW_GAMMA = 0.62
LIGHT_GAMMA = 1.30
SHADOW_MAX_ALPHA = 0.38
LIGHT_MAX_ALPHA = 0.07
ALPHA_STEPS = 32
EDGE_FEATHER_FRACTION = 0.055

CONTOUR_INTERVAL_METRES = 100
CONTOUR_INDEX_INTERVAL_METRES = 500
CONTOUR_SMOOTHING_PASSES = 2
CONTOUR_SIMPLIFY_TOLERANCE_METRES = 140.0
CONTOUR_MIN_LENGTH_METRES = 2500.0
CONTOUR_COORDINATE_DECIMALS = 5

DESCRIPTOR_PATH = PUBLIC_DATA_DIR / "atlas-terrain.json"
PROVENANCE_PATH = PUBLIC_DATA_DIR / "provenance.json"

WEB_MERCATOR_R = 6378137.0


def require_geospatial() -> None:
    if GEOSPATIAL_IMPORT_ERROR is not None:
        raise SystemExit(
            "Install Atlas build dependencies: python -m pip install -r requirements-atlas.txt"
        ) from GEOSPATIAL_IMPORT_ERROR


def read_json(path: Path) -> Any:
    return json.loads(path.read_text())


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"
    )


def write_json_pretty(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n")


def sha256_path(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def verify_source_files(manifest: dict[str, Any], source_dir: Path) -> list[Path]:
    """Refuse to derive anything from bytes the manifest has not pinned."""
    paths: list[Path] = []
    for entry in manifest["source_files"]:
        path = source_dir / entry["name"]
        if not path.is_file():
            raise SystemExit(
                f"missing pinned source tile: {path}\n"
                f"Download it from {entry['resource_url']} into {source_dir}"
            )
        if path.stat().st_size != entry["bytes"]:
            raise SystemExit(f"{entry['name']}: byte count does not match the manifest")
        actual = sha256_path(path)
        if actual != entry["sha256"]:
            raise SystemExit(
                f"{entry['name']}: checksum mismatch; expected {entry['sha256']}, got {actual}"
            )
        paths.append(path)
    return paths


def mercator_y(latitude_degrees: float) -> float:
    return WEB_MERCATOR_R * math.log(
        math.tan(math.pi / 4 + math.radians(latitude_degrees) / 2)
    )


def mercator_x(longitude_degrees: float) -> float:
    return WEB_MERCATOR_R * math.radians(longitude_degrees)


def mercator_latitude(y: float) -> float:
    return math.degrees(2 * math.atan(math.exp(y / WEB_MERCATOR_R)) - math.pi / 2)


def build_target_grid(bbox: tuple[float, float, float, float]) -> dict[str, Any]:
    """A fixed EPSG:3857 grid anchored on the proof extent's north-west corner."""
    west, south, east, north = bbox
    x_west = mercator_x(west)
    y_north = mercator_y(north)
    # Round outwards: the rendered image must always cover the proof extent, never
    # fall a fraction of a pixel short of it.
    width = math.ceil((mercator_x(east) - x_west) / PIXEL_SIZE_METRES_EPSG3857 - 1e-9)
    height = math.ceil((y_north - mercator_y(south)) / PIXEL_SIZE_METRES_EPSG3857 - 1e-9)
    x_east = x_west + width * PIXEL_SIZE_METRES_EPSG3857
    y_south = y_north - height * PIXEL_SIZE_METRES_EPSG3857
    return {
        "width": width,
        "height": height,
        "transform": from_origin(
            x_west, y_north, PIXEL_SIZE_METRES_EPSG3857, PIXEL_SIZE_METRES_EPSG3857
        ),
        "x_west": x_west,
        "x_east": x_east,
        "y_north": y_north,
        "y_south": y_south,
        # The rendered image is Web Mercator, so its lon/lat corners are the exact
        # bbox corners and MapLibre's image source places it without warping error.
        "image_bbox_epsg4326": [
            round(math.degrees(x_west / WEB_MERCATOR_R), 9),
            round(mercator_latitude(y_south), 9),
            round(math.degrees(x_east / WEB_MERCATOR_R), 9),
            round(mercator_latitude(y_north), 9),
        ],
    }


def snap_to_source_grid(value: float, origin: float, resolution: float, *, up: bool) -> float:
    """Align a clip edge to the source sample grid.

    The tiles butt edge to edge. Clipping to an arbitrary bounding box would put
    the mosaic on a grid offset from the samples, and every tile join would come
    back as a one-pixel seam in the hillshade.
    """
    steps = (value - origin) / resolution
    steps = math.ceil(steps - 1e-9) if up else math.floor(steps + 1e-9)
    return origin + steps * resolution


def load_elevation(
    source_paths: list[Path],
    grid: dict[str, Any],
    bbox: tuple[float, float, float, float],
) -> "np.ndarray":
    """Mosaic the pinned tiles, then resample once onto the fixed Mercator grid."""
    west, south, east, north = bbox
    buffer_degrees = SOURCE_CLIP_BUFFER_DEGREES
    datasets = [rasterio.open(path) for path in source_paths]
    try:
        reference = datasets[0]
        resolution_x = reference.transform.a
        resolution_y = -reference.transform.e
        origin_x = min(dataset.bounds.left for dataset in datasets)
        origin_y = max(dataset.bounds.top for dataset in datasets)
        mosaic, mosaic_transform = merge_rasters(
            datasets,
            bounds=(
                snap_to_source_grid(west - buffer_degrees, origin_x, resolution_x, up=False),
                snap_to_source_grid(south - buffer_degrees, origin_y, resolution_y, up=False),
                snap_to_source_grid(east + buffer_degrees, origin_x, resolution_x, up=True),
                snap_to_source_grid(north + buffer_degrees, origin_y, resolution_y, up=True),
            ),
            resampling=Resampling.nearest,
        )
    finally:
        for dataset in datasets:
            dataset.close()

    destination = np.zeros((grid["height"], grid["width"]), dtype="float32")
    reproject(
        source=mosaic[0],
        destination=destination,
        src_transform=mosaic_transform,
        src_crs="EPSG:4326",
        dst_transform=grid["transform"],
        dst_crs="EPSG:3857",
        resampling=Resampling.average,
        num_threads=1,
    )
    return destination


def row_latitudes(grid: dict[str, Any]) -> "np.ndarray":
    rows = np.arange(grid["height"], dtype="float64")
    y = grid["y_north"] - (rows + 0.5) * PIXEL_SIZE_METRES_EPSG3857
    return np.degrees(2 * np.arctan(np.exp(y / WEB_MERCATOR_R)) - np.pi / 2)


def hillshade(elevation: "np.ndarray", grid: dict[str, Any]) -> "np.ndarray":
    """Horn slope/aspect hillshade, corrected for Web Mercator scale inflation.

    A Mercator grid cell is `1 / cos(latitude)` too wide in ground terms. Without
    that correction the same hill would look steeper the further north it sits.
    """
    padded = np.pad(elevation.astype("float64"), 1, mode="edge")
    a = padded[0:-2, 0:-2]
    b = padded[0:-2, 1:-1]
    c = padded[0:-2, 2:]
    d = padded[1:-1, 0:-2]
    f = padded[1:-1, 2:]
    g = padded[2:, 0:-2]
    h = padded[2:, 1:-1]
    i = padded[2:, 2:]

    latitudes = row_latitudes(grid)
    ground_cell = (
        PIXEL_SIZE_METRES_EPSG3857 * np.cos(np.radians(latitudes))
    ).reshape(-1, 1)

    dz_dx = ((c + 2.0 * f + i) - (a + 2.0 * d + g)) / (8.0 * ground_cell)
    # Row index grows southwards, so the northward gradient flips sign.
    dz_dy = ((a + 2.0 * b + c) - (g + 2.0 * h + i)) / (8.0 * ground_cell)

    slope = np.arctan(HILLSHADE_Z_FACTOR * np.hypot(dz_dx, dz_dy))
    aspect = np.arctan2(dz_dy, -dz_dx)

    zenith = math.radians(90.0 - HILLSHADE_ALTITUDE_DEGREES)
    azimuth = math.radians(360.0 - HILLSHADE_AZIMUTH_DEGREES + 90.0)
    shade = np.cos(zenith) * np.cos(slope) + np.sin(zenith) * np.sin(slope) * np.cos(
        azimuth - aspect
    )
    return np.clip(shade, -1.0, 1.0)


def edge_feather(grid: dict[str, Any]) -> "np.ndarray":
    """A cosine ramp so the relief patch dissolves instead of ending in a rectangle."""
    def ramp(length: int) -> "np.ndarray":
        band = max(1, int(round(length * EDGE_FEATHER_FRACTION)))
        values = np.ones(length, dtype="float64")
        edge = 0.5 - 0.5 * np.cos(np.pi * (np.arange(band) + 0.5) / band)
        values[:band] = edge
        values[length - band :] = edge[::-1]
        return values

    return np.outer(ramp(grid["height"]), ramp(grid["width"]))


def hillshade_image(shade: "np.ndarray", grid: dict[str, Any]) -> "Image.Image":
    """Quantise the hillshade into a small shadow/light palette with alpha.

    The overlay only ever darkens or lightens; it never paints a colour of its
    own over the wine geography underneath.
    """
    neutral = math.cos(math.radians(90.0 - HILLSHADE_ALTITUDE_DEGREES))
    deviation = shade - neutral
    feather = edge_feather(grid)

    shadow = (
        np.clip(-deviation / HILLSHADE_RESPONSE_SCALE, 0.0, 1.0) ** SHADOW_GAMMA
    ) * feather
    light = (
        np.clip(deviation / HILLSHADE_RESPONSE_SCALE, 0.0, 1.0) ** LIGHT_GAMMA
    ) * feather

    shadow_step = np.rint(shadow * ALPHA_STEPS).astype("int16")
    light_step = np.rint(light * ALPHA_STEPS).astype("int16")

    index = np.zeros(shade.shape, dtype="uint8")
    is_shadow = deviation < 0.0
    index = np.where(is_shadow & (shadow_step > 0), shadow_step, index)
    index = np.where(~is_shadow & (light_step > 0), ALPHA_STEPS + light_step, index)
    index = index.astype("uint8")

    palette: list[int] = [0, 0, 0]
    alpha: list[int] = [0]
    for step in range(1, ALPHA_STEPS + 1):
        palette.extend(SHADOW_INK)
        alpha.append(int(round(255 * SHADOW_MAX_ALPHA * step / ALPHA_STEPS)))
    for step in range(1, ALPHA_STEPS + 1):
        palette.extend(LIGHT_INK)
        alpha.append(int(round(255 * LIGHT_MAX_ALPHA * step / ALPHA_STEPS)))

    image = Image.fromarray(index, mode="P")
    image.putpalette(palette + [0] * (768 - len(palette)))
    image.info["transparency"] = bytes(alpha)
    return image


def smooth(elevation: "np.ndarray", passes: int) -> "np.ndarray":
    """Fixed 3×3 binomial smoothing; keeps contours readable instead of noisy."""
    result = elevation.astype("float64")
    for _ in range(passes):
        padded = np.pad(result, 1, mode="edge")
        result = (
            padded[0:-2, 0:-2]
            + 2.0 * padded[0:-2, 1:-1]
            + padded[0:-2, 2:]
            + 2.0 * padded[1:-1, 0:-2]
            + 4.0 * padded[1:-1, 1:-1]
            + 2.0 * padded[1:-1, 2:]
            + padded[2:, 0:-2]
            + 2.0 * padded[2:, 1:-1]
            + padded[2:, 2:]
        ) / 16.0
    return result


def contour_features(elevation: "np.ndarray", grid: dict[str, Any]) -> list[dict[str, Any]]:
    smoothed = smooth(elevation, CONTOUR_SMOOTHING_PASSES)
    xs = grid["x_west"] + (np.arange(grid["width"]) + 0.5) * PIXEL_SIZE_METRES_EPSG3857
    ys = grid["y_north"] - (np.arange(grid["height"]) + 0.5) * PIXEL_SIZE_METRES_EPSG3857
    generator = contourpy.contour_generator(
        x=xs, y=ys, z=smoothed, name="serial", line_type=contourpy.LineType.SeparateCode
    )
    transformer = Transformer.from_crs("EPSG:3857", "EPSG:4326", always_xy=True)

    highest = int(math.floor(float(np.nanmax(smoothed)) / CONTOUR_INTERVAL_METRES))
    features: list[dict[str, Any]] = []
    for step in range(1, highest + 1):
        level = step * CONTOUR_INTERVAL_METRES
        lines, _codes = generator.lines(float(level))
        rendered = 0
        for vertices in lines:
            if len(vertices) < 2:
                continue
            geometry = LineString(vertices)
            if geometry.length < CONTOUR_MIN_LENGTH_METRES:
                continue
            simplified = geometry.simplify(
                CONTOUR_SIMPLIFY_TOLERANCE_METRES, preserve_topology=False
            )
            if simplified.is_empty or len(simplified.coords) < 2:
                continue
            longitudes, latitudes = transformer.transform(
                [x for x, _ in simplified.coords], [y for _, y in simplified.coords]
            )
            coordinates = [
                [
                    round(float(longitude), CONTOUR_COORDINATE_DECIMALS),
                    round(float(latitude), CONTOUR_COORDINATE_DECIMALS),
                ]
                for longitude, latitude in zip(longitudes, latitudes)
            ]
            deduplicated = [coordinates[0]]
            for point in coordinates[1:]:
                if point != deduplicated[-1]:
                    deduplicated.append(point)
            if len(deduplicated) < 2:
                continue
            feature_id = f"terrain-contour-{level:05d}-{rendered:04d}"
            rendered += 1
            features.append(
                {
                    "type": "Feature",
                    "id": feature_id,
                    "geometry": {"type": "LineString", "coordinates": deduplicated},
                    "properties": {
                        "source_feature_id": feature_id,
                        "elevation_metres": level,
                        "contour_class": (
                            "index"
                            if level % CONTOUR_INDEX_INTERVAL_METRES == 0
                            else "intermediate"
                        ),
                        "feature_type": "elevation_contour",
                        "representation_type": "derived_spatial_product",
                        "representation_label": (
                            "Contour derived from the Copernicus DEM surface model; "
                            "not a vineyard, parcel or legal boundary"
                        ),
                        "source_dataset_id": TERRAIN_DATASET_ID,
                    },
                }
            )
    return features


def artifact_metadata(
    path: Path,
    role: str,
    *,
    fmt: str,
    derived_from: list[str],
    feature_count: int | None = None,
    record_count: int | None = None,
    pixel_width: int | None = None,
    pixel_height: int | None = None,
) -> dict[str, Any]:
    value: dict[str, Any] = {
        "path": path.relative_to(ROOT).as_posix(),
        "format": fmt,
        "sha256": sha256_path(path),
        "bytes": path.stat().st_size,
        "role": role,
        "product_class": "derived_spatial_product",
        "derived_from": derived_from,
    }
    if feature_count is not None:
        value["feature_count"] = feature_count
    if record_count is not None:
        value["record_count"] = record_count
    if pixel_width is not None:
        value["pixel_width"] = pixel_width
    if pixel_height is not None:
        value["pixel_height"] = pixel_height
    return value


def transformations(grids: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    steps: list[dict[str, Any]] = [
        {
            "order": 1,
            "operation": "verify_pinned_source_files",
            "parameters": {
                "algorithm": "sha256",
                "file_count": sum(len(extent["source_files"]) for extent in TERRAIN_EXTENTS),
                "refuse_on_mismatch": True,
            },
        }
    ]
    order = 2
    for extent in TERRAIN_EXTENTS:
        grid = grids[extent["id"]]
        bbox = extent["bbox"]
        common = {"extent_id": extent["id"]}
        extent_steps = [
            (
                "mosaic_and_clip_source_observation",
                {
                    **common,
                    "source_file_count": len(extent["source_files"]),
                    "clip_bbox_epsg4326": list(bbox),
                    "clip_buffer_degrees": SOURCE_CLIP_BUFFER_DEGREES,
                    "merge_resampling": "nearest",
                },
            ),
            (
                "reproject_to_display_grid",
                {
                    **common,
                    "target_crs": "EPSG:3857",
                    "pixel_size_metres": PIXEL_SIZE_METRES_EPSG3857,
                    "resampling": "average",
                    "grid_width": grid["width"],
                    "grid_height": grid["height"],
                    "effective_ground_resolution_metres": round(
                        PIXEL_SIZE_METRES_EPSG3857
                        * math.cos(math.radians((bbox[1] + bbox[3]) / 2)),
                        1,
                    ),
                },
            ),
            (
                "hillshade_horn",
                {
                    **common,
                    "azimuth_degrees": HILLSHADE_AZIMUTH_DEGREES,
                    "altitude_degrees": HILLSHADE_ALTITUDE_DEGREES,
                    "z_factor": HILLSHADE_Z_FACTOR,
                    "mercator_scale_correction": True,
                },
            ),
            (
                "quantise_to_shadow_and_light_overlay",
                {
                    **common,
                    "alpha_steps": ALPHA_STEPS,
                    "response_scale": HILLSHADE_RESPONSE_SCALE,
                    "shadow_rgb": list(SHADOW_INK),
                    "shadow_gamma": SHADOW_GAMMA,
                    "shadow_max_alpha": SHADOW_MAX_ALPHA,
                    "light_rgb": list(LIGHT_INK),
                    "light_gamma": LIGHT_GAMMA,
                    "light_max_alpha": LIGHT_MAX_ALPHA,
                    "edge_feather_fraction": EDGE_FEATHER_FRACTION,
                    "output_format": "8-bit paletted PNG with per-index alpha",
                },
            ),
            (
                "contour_elevation_surface",
                {
                    **common,
                    "smoothing": "3x3 binomial",
                    "smoothing_passes": CONTOUR_SMOOTHING_PASSES,
                    "interval_metres": CONTOUR_INTERVAL_METRES,
                    "index_interval_metres": CONTOUR_INDEX_INTERVAL_METRES,
                    "simplify_tolerance_metres_epsg3857": CONTOUR_SIMPLIFY_TOLERANCE_METRES,
                    "minimum_length_metres_epsg3857": CONTOUR_MIN_LENGTH_METRES,
                    "coordinate_decimals": CONTOUR_COORDINATE_DECIMALS,
                },
            ),
        ]
        for operation, parameters in extent_steps:
            steps.append({"order": order, "operation": operation, "parameters": parameters})
            order += 1
    return steps


def build_extent_descriptor(
    manifest: dict[str, Any],
    extent: dict[str, Any],
    grid: dict[str, Any],
    elevation: "np.ndarray",
    feature_count: int,
) -> dict[str, Any]:
    west, south, east, north = grid["image_bbox_epsg4326"]
    return {
        "id": extent["id"],
        "label": extent["label"],
        "proof_extent": {
            "bbox_epsg4326": list(extent["bbox"]),
            "description": extent["description"],
        },
        "hillshade": {
            "path": f"./data/{extent['hillshade_path'].name}",
            "image_bbox_epsg4326": grid["image_bbox_epsg4326"],
            # MapLibre image-source corner order: top-left, top-right, bottom-right, bottom-left.
            "image_coordinates": [
                [west, north],
                [east, north],
                [east, south],
                [west, south],
            ],
            "projection": "EPSG:3857",
            "pixel_size_metres_epsg3857": PIXEL_SIZE_METRES_EPSG3857,
            "pixel_width": grid["width"],
            "pixel_height": grid["height"],
            "illumination": {
                "azimuth_degrees": HILLSHADE_AZIMUTH_DEGREES,
                "altitude_degrees": HILLSHADE_ALTITUDE_DEGREES,
                "z_factor": HILLSHADE_Z_FACTOR,
            },
        },
        "contours": {
            "path": f"./data/{extent['contour_path'].name}",
            "interval_metres": CONTOUR_INTERVAL_METRES,
            "index_interval_metres": CONTOUR_INDEX_INTERVAL_METRES,
            "feature_count": feature_count,
        },
        "elevation": {
            "unit": manifest["measurement"]["unit"],
            "variable": manifest["measurement"]["variable"],
            "vertical_reference": manifest["measurement"]["vertical_reference"],
            "minimum": round(float(np.min(elevation)), 1),
            "maximum": round(float(np.max(elevation)), 1),
            "native_resolution": manifest["measurement"]["native_resolution"],
            "scale_limitations": manifest["measurement"]["scale_limitations"],
            "uncertainty": manifest["measurement"]["uncertainty"],
        },
    }


def build_descriptor(
    manifest: dict[str, Any],
    extents: list[dict[str, Any]],
    recipe: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "generated_from": [
            TERRAIN_MANIFEST_PATH.relative_to(ROOT).as_posix(),
            ".cache/atlas/terrain/*.tif (pinned, never committed)",
        ],
        "release": TERRAIN_RELEASE,
        "source_dataset_id": TERRAIN_DATASET_ID,
        "product_class": "derived_spatial_product",
        "attribution": manifest["license"]["attribution_text"],
        "meaning": (
            "Shaded relief and contour lines derived from a public elevation model. "
            "They show the shape of the ground. They do not describe vineyard land, and "
            "nothing about slope or height here is evidence for how a wine tastes."
        ),
        "terrains": extents,
        "recipe": recipe,
    }


def regenerate_provenance() -> None:
    """Rewrite provenance.json from every manifest on disk.

    The INAO reconciliation counters belong to the geography build, which needs
    network access to its pinned archives. They are carried forward untouched so
    a terrain rebuild never silently invents or drops them.
    """
    existing = read_json(PROVENANCE_PATH)
    manifests = [read_json(path) for path in sorted(MANIFEST_DIR.glob("*.json"))]
    write_json(
        PROVENANCE_PATH,
        build_provenance(manifests, existing["inao_reconciliation"]),
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=DEFAULT_SOURCE_DIR,
        help="Directory holding the pinned Copernicus DEM tiles; never committed.",
    )
    args = parser.parse_args()

    require_geospatial()
    manifest = read_json(TERRAIN_MANIFEST_PATH)
    source_paths = verify_source_files(manifest, args.source_dir.resolve())
    source_paths_by_name = {path.name: path for path in source_paths}

    grids = {extent["id"]: build_target_grid(extent["bbox"]) for extent in TERRAIN_EXTENTS}
    recipe = transformations(grids)
    terrain_descriptors: list[dict[str, Any]] = []
    terrain_results: list[dict[str, Any]] = []
    for extent in TERRAIN_EXTENTS:
        grid = grids[extent["id"]]
        selected_paths = [source_paths_by_name[name] for name in extent["source_files"]]
        elevation = load_elevation(selected_paths, grid, extent["bbox"])

        image = hillshade_image(hillshade(elevation, grid), grid)
        extent["hillshade_path"].parent.mkdir(parents=True, exist_ok=True)
        image.save(extent["hillshade_path"], format="PNG", optimize=True)

        features = contour_features(elevation, grid)
        write_json(extent["contour_path"], {"type": "FeatureCollection", "features": features})
        terrain_descriptors.append(
            build_extent_descriptor(manifest, extent, grid, elevation, len(features))
        )
        terrain_results.append(
            {"extent": extent, "grid": grid, "feature_count": len(features)}
        )

    descriptor = build_descriptor(manifest, terrain_descriptors, recipe)
    write_json(DESCRIPTOR_PATH, descriptor)

    manifest["transformations"] = recipe
    artifacts: list[dict[str, Any]] = []
    descriptor_dependencies = [TERRAIN_DATASET_ID]
    for result in terrain_results:
        extent = result["extent"]
        grid = result["grid"]
        artifacts.extend(
            [
                artifact_metadata(
                    extent["hillshade_path"],
                    f"{extent['label']} shaded-relief overlay",
                    fmt="PNG",
                    derived_from=[TERRAIN_DATASET_ID],
                    pixel_width=grid["width"],
                    pixel_height=grid["height"],
                ),
                artifact_metadata(
                    extent["contour_path"],
                    f"{extent['label']} elevation contour lines",
                    fmt="GeoJSON",
                    derived_from=[TERRAIN_DATASET_ID],
                    feature_count=result["feature_count"],
                ),
            ]
        )
        descriptor_dependencies.extend(
            [
                extent["hillshade_path"].relative_to(ROOT).as_posix(),
                extent["contour_path"].relative_to(ROOT).as_posix(),
            ]
        )
    artifacts.append(
        artifact_metadata(
            DESCRIPTOR_PATH,
            "Terrain descriptor: bounded extents, placement, intervals and attribution for the Atlas",
            fmt="JSON",
            derived_from=descriptor_dependencies,
        )
    )
    manifest["derived_artifacts"] = sorted(artifacts, key=lambda item: item["path"])
    write_json_pretty(TERRAIN_MANIFEST_PATH, manifest)

    regenerate_provenance()

    summaries = []
    for terrain, result in zip(terrain_descriptors, terrain_results, strict=True):
        extent = result["extent"]
        grid = result["grid"]
        summaries.append(
            f"{extent['id']}={grid['width']}x{grid['height']} "
            f"hillshade_bytes={extent['hillshade_path'].stat().st_size} "
            f"contours={result['feature_count']} contour_bytes={extent['contour_path'].stat().st_size} "
            f"elevation={terrain['elevation']['minimum']}..{terrain['elevation']['maximum']}"
        )
    print("PASS " + "; ".join(summaries))


if __name__ == "__main__":
    main()
